/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721PresetMinterPauserAutoIdUpgradeable__factory } from "./ERC721PresetMinterPauserAutoIdUpgradeable__factory";
