/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDNTMultiTransfer,
  IDNTMultiTransferInterface,
} from "../../../../contracts/audit/interfaces/IDNTMultiTransfer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
      {
        internalType: "string[]",
        name: "utilities",
        type: "string[]",
      },
    ],
    name: "transferFromUtilities",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDNTMultiTransfer__factory {
  static readonly abi = _abi;
  static createInterface(): IDNTMultiTransferInterface {
    return new utils.Interface(_abi) as IDNTMultiTransferInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDNTMultiTransfer {
    return new Contract(address, _abi, signerOrProvider) as IDNTMultiTransfer;
  }
}
