/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { DappsStaking } from "./DappsStaking";
export type { IAdaptersDistributor } from "./IAdaptersDistributor";
export type { IDNT } from "./IDNT";
export type { IDNTMultiTransfer } from "./IDNTMultiTransfer";
export type { ILiquidStaking } from "./ILiquidStaking";
export type { INDistributor } from "./INDistributor";
export type { INFTDistributor } from "./INFTDistributor";
export type { IPartnerHandler } from "./IPartnerHandler";
