/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPartnerHandler,
  IPartnerHandlerInterface,
} from "../../../../contracts/common/interfaces/IPartnerHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "calc",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPartnerHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IPartnerHandlerInterface {
    return new utils.Interface(_abi) as IPartnerHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPartnerHandler {
    return new Contract(address, _abi, signerOrProvider) as IPartnerHandler;
  }
}
