/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as nAstrOldSol from "./nASTROld.sol";
export type { nAstrOldSol };
export type { LiquidStakingOld } from "./LiquidStakingOld";
export type { NDistributorOld } from "./NDistributorOld";
